### ISSUE TITLE
Radio zero value 

### ISSUE THREAD

**Issue by gamevnlc** [spatie/laravel-html#100]
I tried to make radio have value is zero. It's always change value from 0 to 1. Is it a bug?
My code 
`            {{ html()->radio('is_default', $clientType->is_default == 0, 0)->id('form-radio-default-2')->class('form-check-input') }}`

![image](https://user-images.githubusercontent.com/2215185/40649788-5ada1e00-6364-11e8-9112-f07a64b6828e.png)

**Comment by gamevnlc** [comment]
Yep i think so, how could i avoid this ?

**Comment by sebastiandedeyne** [comment]
If you wan't to ignore the model's and old values for custom behavior, use a named method to set the value instead.

```blade
{{ html()->radio('is_default')
  ->checked($clientType->is_default == 0)
  ->value(0)
  ->id('form-radio-default-2')
  ->class('form-check-input') }}
```
