### ISSUE TITLE
Non-unique element ID's generated on various input field attributes

### ISSUE THREAD

**Issue by brentkozjak** [spatie/laravel-html#102]
Expanding upon the closed issue #85, other input field attributes such as "method", "email" and "password" are creating duplicate "id" attributes resulting in the same errors in the browser console.  For example, in my scenario I have both a modal login form and a login page, so when using: `html()->email('email') ...` and `html()->password('password') ...` more than once on a single page, I receive console errors.

Example of Chrome console error when using multiple forms that specify a method:

```
[DOM] Found 6 elements with non-unique id #_method: (More info: https://goo.gl/9p2vKq)
```

**Comment by kiwikefei** [comment]
same page, different forms switched by tab will automatically add same hidden inputs with id="_method" which causes the `non-unique id #_method` error in chrome console. not a big deal but a bit annoying for an OCD developer 😃

**Comment by sebastiandedeyne** [comment]
This package will never be smart enough to foresee this case. If you have multiple fields with the same name on a single page, I suggest you explicitly declare your own id's.

```blade
{{ html()->password('password')->id('login_password') }}
{{ html()->password('password')->id('register_password') }}
```

**Comment by skys215** [comment]
how to remove `id` attribtue for multiple field? I'm passing as an array to controller.

I've tried passing `null` into `id()`, but it only add `id` as an property, it doesn't remove `id` attribute.

```
{{ html()->text('role_names[]') }}
{{ html()->text('role_names[]') }}
```
