### ISSUE TITLE
Add Attributes to Html Form() Method

### ISSUE THREAD

**Issue by Lavannyamuthu** [spatie/laravel-html#106]
Add Attributes to form() method so that we can any class,autocomplete off kind of attributes. like the following:

public function form($method = 'POST', $action = null, $attributes = null)
    {
        $method = strtoupper($method);
        $form = Form::create();

        // If Laravel needs to spoof the form's method, we'll append a hidden
        // field containing the actual method
        if (in_array($method, ['DELETE', 'PATCH', 'PUT'])) {
            $form = $form->addChild($this->hidden('_method')->value($method));
        }

        // On any other method that get, the form needs a CSRF token
        if ($method !== 'GET') {
            $form = $form->addChild($this->token());
        }

        return $form
            ->method($method === 'GET' ? 'GET' : 'POST')
            ->attributes($attributes)
            ->attributeIf($action, 'action', $action);
    }

**Comment by aalaap** [comment]
You can do this by setting the attributes directly on the `form()` method *before calling `open()`*, like this:

    {{ html()->form('POST', '/foo/bar')->attribute('class', 'bar-form')->open() }}
