### ISSUE TITLE
Allow boolean to all Required methods

### ISSUE THREAD

**Issue by harrysbaraini** [spatie/laravel-html#108]
Hello, I've found a [this PR](https://github.com/spatie/laravel-html/pull/90) , but it only changed Input, but there are required methods in other elements, like [File class](https://github.com/spatie/laravel-html/blob/45da25ffb6cf44449d2ce1dcaf39e61366bcf185/src/Elements/File.php#L35).

Is there anything that prevents updating other `required` methods?
Otherwise, I'd be glad to open a PR.

**Comment by sebastiandedeyne** [comment]
Sounds good, go for it!
