### ISSUE TITLE
@lang throws exception Laravel 5.7

### ISSUE THREAD

**Issue by turbo124** [spatie/laravel-html#109]
using the following throws an exception in Laravel 5.7

{{ html()->email('email')->placeholder(@lang('texts.email_address'))->class('input is-large') }}

error:
syntax error, unexpected '<'

 <?php echo e(html()->email('email')->placeholder(<?php echo app('translator')->getFromJson('texts.email_address'); ?>)->class('input is-large')); ?>

However the following works fine.
{{ html()->email('email')->placeholder(__('texts.email_address'))->class('input is-large') }}

**Comment by brendt** [comment]
`trans()` or `__()` are both valid options, `@lang` won't work because, as @htulibacki said, you're in a PHP context there, not Blade.
