### ISSUE TITLE
Wrong checkbox tick on failed validation using modelForm

### ISSUE THREAD

**Issue by lklion** [spatie/laravel-html#113]
Using `modelForm` checkboxes are checked correctly with model values but, if there is a validation error (eg when a FormRequest fail) and I have unticked a checkbox, this is checked again.

An example of what I mean:
```php
{{ html()->modelForm($model, 'PUT', route('model.update', $model)->open() }}
        {{ html()->checkbox('service[delivery]') }}
        {{ html()->checkbox('service[graphic]') }}
        {{ html()->checkbox('service[web]') }}
// ...
```

1. Imagine that "service" value on database ["web" => 1]
2. Untick the "web" checkbox and set "delivery" as checked
3. Submit the form with a FormRequest that fail (eg for another required field)

I expect that the "web" checkbox is unticked and "delivery" is checked ... instead are both checked.

I have notice that the `old()` method (https://github.com/spatie/laravel-html/blob/master/src/Html.php#L497) returns the model value if there isn't an "old" value in session. This can be right for other input types but not for checkboxes.

Thoughts?

**Comment by sebastiandedeyne** [comment]
Unchecked checkboxes unfortunately don't get sent to the server, this doens't have anything to do with how we generate HTML. I suggest you look into this workaround: https://stackoverflow.com/a/2520970

**Comment by billmn** [comment]
@sebastiandedeyne Mmmmm, personally I think this issue could be a bug.

It's true that unchecked checkboxes don't get sent to the server but the current `modelForm` method doesn't fill checkboxes correctly.

This issue could be simply fixed by checking that session old inputs array is empty.
There is no need to retrieve value from the model after a submit.

If it's ok for you I can made a PR.

## CURRENT
```php
protected function old($name, $value = null)
{
    if (empty($name)) {
        return;
    }

    // Convert array format (sth[1]) to dot notation (sth.1)
    $name = preg_replace('/\[(.+)\]/U', '.$1', $name);

    // If there's no default value provided, and the html builder currently
    // has a model assigned, try to retrieve a value from the model.
    if (empty($value) && $this->model) {
        $value = data_get($this->model, $name) ?? '';
    }

    return $this->request->old($name, $value);
}
```

## FIXED
```php
protected function old($name, $value = null)
{
    if (empty($name)) {
        return;
    }

    // Convert array format (sth[1]) to dot notation (sth.1)
    $name = preg_replace('/\[(.+)\]/U', '.$1', $name);

    // If there's no default value provided, and the html builder currently
    // has a model assigned, try to retrieve a value from the model.
    if (empty($value) && $this->model && empty($this->request->old())) { // <--- [[ FIX ]]
        $value = data_get($this->model, $name) ?? '';
    }

    return $this->request->old($name, $value);
}
```

**Comment by sebastiandedeyne** [comment]
Sounds good, feel free to send a PR!

**Comment by Nix-id** [comment]
@billmn 
hi
affter this fix
``
if (empty($value) && $this->model && empty($this->request->old()))
``

if i manualy set value to one field with
``
session(['_old_input.key' => $request->get('key', $default)]);
``

then all other fields in form are empty.

it must be changed to 
``
if (empty($value) && $this->model && empty($this->request->old( $name )))
``
