### ISSUE TITLE
Pretty print HTML

### ISSUE THREAD

**Issue by fsou** [spatie/laravel-html#128]
Hi!

I am trying to display a list of buttons using the HTML builder.

When using inside a blade template, I can manually create the buttons and each button creates it's own line of HTML.

```
{{ html()->span()->class('menu actions')->open() }}
  {{ html()->button('save') }}
  {{ html()->buttons('cancel') }}
{{ html()->span()->close() }}
```

When creating the list of buttons using a Renderer, the items wont get a line for each one.
```

$result = html()->span()->class('menu actions')->open();

$result .= $items->map(function ($item)  {
                return (string) html()->button($item);
        });
$result = html()->span()->close();

return $result;
```

The issue here is that as side effect, I'm getting the buttons without any space between them, when using the renderer.

Thank you,
Filipe

**Comment by atymic** [comment]
One way to handle this would be with CSS. I'm not sure the behaviour should be changed, as it would be a BC break for anything relying on the old behaviour.

**Comment by fsou** [comment]
As a Workaround I've added a blank space after each button, that way the items wont be glued together.
`->child(' ');`

CSS would handle this, but I still consider it as an abnormal behaviour... The BC break can also be handled using CSS.

**Comment by sebastiandedeyne** [comment]
I consider this expected behaviour. Whitespace should be added explicitly.
