### ISSUE TITLE
v2 documentation returns 500 error

### ISSUE THREAD

**Issue by ronydebnath** [spatie/laravel-html#130]
while v1 is working fine, v2 docs returns error 500, Please have a look and fix it.
 
![screenshot from 2019-02-27 22-54-52](https://user-images.githubusercontent.com/10370201/53508010-2be62100-3ae3-11e9-9f29-8b6aa3600351.png)

**Comment by atymic** [comment]
I think this issue can be closed, the documentation seems to be working now:
https://docs.spatie.be/laravel-html/v2/introduction
