### ISSUE TITLE
When using html()->date() the model value is not populated

### ISSUE THREAD

**Issue by rabol** [spatie/laravel-html#131]
Hi

I use the html()->date(....) with a model where the date is a timestamp, but when the form is shown, the value in the model is not pre-set

{{ html()->date('start_date')
                                ->class('form-control')
                                ->placeholder('Enter date')
                                ->required() }}

**Comment by rabol** [comment]
one have to format the value e.g like this date_format($date_value, "Y-m-d")

**Comment by atymic** [comment]
I'd be happy to create a PR for this, should be a pretty simple fix.

**Comment by freekmurze** [comment]
Go ahead @atymic 

Be sure to include some tests 👍
