### ISSUE TITLE
Handling Relationships

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-html#133]
I'm just getting started with the package so I may be doing this incorrectly, however I'm curious if this package handles relationships?

I want to use my form for creating and editing, but an error is thrown if `$user` doesn't exist, so I'm doing this now, which seems clunky. Is there another way?

```
@if(isset($user))
    {{ html()->text('hobbies', $user->data->hobbies) }}
@else
    {{ html()->text('hobbies') }}
@endif
```

**Comment by atymic** [comment]
Providing you are running PHP 7, you can just use the null coalesce operator like so:
```php
 {{ html()->text('hobbies', $user->data->hobbies ?? null) }}
```
