### ISSUE TITLE
html->password() fill hashed value from DB in password input

### ISSUE THREAD

**Issue by YordanovBg** [spatie/laravel-html#139]
I use html->password() with model form, in my case password is part of hidden attributes, but in rendered html i see hashed value 
"\<input type="password" name="password" id="password" value="$2y$10$gPIv1ljqz7z2IEL/IgI3YOF..." class="form-control">\"

    protected $hidden = [
        'password', 'remember_token',
    ];

**Comment by atymic** [comment]
As per the laravel docs, `$hidden` only hides the attributes from serialization (and not from direct access)
https://laravel.com/docs/5.8/eloquent-serialization#hiding-attributes-from-json
