### ISSUE TITLE
Number element

### ISSUE THREAD

**Issue by fdrobnic** [spatie/laravel-html#142]
Please provide a method to generate numeric input element like this:

    /**
     * @param string|null $name
     * @param string|null $value
     * @param string|null $step
     *
     * @return \Spatie\Html\Elements\Input
     */
    public function number($name = null, $value = null, $step = null)
    {
        return $this->input('number', $name, $value)
                ->attributeIf($step, 'step', $step);
    }

This should go probably to src/Html.php after the method `multiselect()`.

TIA

**Comment by sebastiandedeyne** [comment]
Feel free to send over a PR :)

**Comment by riasvdv** [comment]
Thanks @fdrobnic for your work, merged and tagged!
