### ISSUE TITLE
Populate select with collection

### ISSUE THREAD

**Issue by Larsklopstra** [spatie/laravel-html#144]
I've been facing an issue where I can't populate the select menu with a collection from my database.

```
// Controller
$courses = Course::all();

return view('...', compact('courses'));

// View
{{ html()->select('course', $courses) }}
```

A course is just a simple object with an `id`, `name` and timestamps.

**What happens?**

Instead of seeing the name I see the object being printed as JSON.

**What did I expect?**

I expected the `value` to be the `id` with the `name` as text

**Comment by sebastiandedeyne** [comment]
Options expect an associative array in a `value => label` format.

Try `html()->select('course', $courses->pluck('name', 'id')`.
