### ISSUE TITLE
Automated Error Class Handling?

### ISSUE THREAD

**Issue by tekook** [spatie/laravel-html#151]
Hi there,

since we are using this lib for **Laravel**, why not add a handling for an automated error class?

Currently I'm adding the "is-invalid" class by checking if the ErrorBag has the corresponding attribute in it.

`html()->input('name')->addClass($errors->has('name') ? 'is-invalid' : '')`

We could easily access the Request on rendering the InputElement and check for the ErrorBag.
We should be able to provide a custom class name like this:

`html()->input('name')->errorClass('is-invalid')`

Maybe provide a default application wide error classname for easier use as a static property.

What do you think?

Kind Regards,
Julian

**Comment by sebastiandedeyne** [comment]
Gonna hold off on this for now. I think this would be a but too opinionated for the package.

**Comment by raulpacheco2k** [comment]
Any news on this? This would be very interesting in the package, I particularly miss this functionality.
