### ISSUE TITLE
Plugins attribute didn't worked

### ISSUE THREAD

**Issue by FareedR** [spatie/laravel-html#155]
I don't know whether plugin issue or this package issue. If I using traditional way , it worked correctly . If I using this package method . Somehow the placeholder didn't worked. This is my code

Plugins used : https://select2.org/
Traditional way
`
    <select name="signal[]" class="form-control" data-toggle="select2" data-placeholder="Signal">
        <option></option>
        @foreach($signals as $signal)
        <option value="{{ $signal['value'] }}">{{ $signal['text'] }}</option>
        @endforeach
    </select>
`

This package method
`{{ html()->select('signal[]', $signals, '')->class('form-control')->attributes(['data-toggle' => 'select2', 'data-placeholder' => 'Signal']) }}`

Looking forward into this  💃

**Comment by sebastiandedeyne** [comment]
Could you also share the HTML that the package renders so we can compare with the traditional way?
