### ISSUE TITLE
"Readonly" is a reserved keyword in PHP 8.1

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-html#170]
We're having an issue using `spatie/laravel-html` in combination with `barryvdh/laravel-ide-helper`.

Running `php artisan ide-helper:generate -vvvv` throws an exception on the `Spatie\Html\Elements\Input` class:

```
PhpParser\Error

Syntax error, unexpected T_READONLY on line 23
```

Checking the `Input` class, line 23, it imports a class called `Readonly`. In PHP 8.1, I suppose this is a reserved keyword. Even though 8.1 isn't released yet, https://github.com/nikic/PHP-Parser seemingly already checks this.

Related issue: https://github.com/nikic/PHP-Parser/issues/799
Introduced here: https://github.com/nikic/PHP-Parser/pull/796

From the `ide-helper` package, we can't define the PHP version to target, so we can't work around this. I think the only solution is to either not use the `ide-helper` package or rename the `Readonly` class in this package. There's no way to exclude files from within the `ide-helper` config, it seems.

I can whip up a PR to rename this (will be necessary if you want to support 8.1), however not sure what to name it then. Any preference? `ReadonlyAttribute`?

**Comment by Nielsvanpach** [comment]
Fair point, a PR would be welcome for this. I'll have a look at the CI of this package today

**Comment by freekmurze** [comment]
This has been addressed in v3 of the package, which is now compatible with PHP 8.1
