### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by filipveschool** [spatie/laravel-html#32]
Hi, How can we load translated strings through the HTML helpers? like the function @lang('...') is in the blade directives?

**Comment by bobbybouwmann** [comment]
Hi, Why dont you just call the text helper with a translation string in your application? 
```
html()->span()->text(trans('some-translation-string');
```

**Comment by sebastiandedeyne** [comment]
What @bobbybouwmann said!

This package uses plain php, so you can use any of Laravel's localization helpers (`trans`, `trans_choice` & `__`)

https://laravel.com/docs/master/localization#retrieving-translation-strings
