### ISSUE TITLE
How to create grouped select lists?

### ISSUE THREAD

**Issue by pr4xx** [spatie/laravel-html#37]
Is it possible to generate grouped select lists like:

`
[
    'Cats' => ['leopard' => 'Leopard'],
    'Dogs' => ['spaniel' => 'Spaniel'],
]
`

Much like [Generating A Grouped List](https://laravelcollective.com/docs/master/html)

Cheers

**Comment by roni-estein** [comment]
Hi Guys, interesting project, I'd like to implement this into a current project, but I think I have to change my thinking on this a bit. Any idea of where how this might be implemented, or if I'm using this in the wrong way. When I am running `$this->validate($request)` in my controller, it will pull my back to my blade file form with errors. Where is the best place to embed the error code in here as an example:

```
{{
    html()->div()->class('form-wrap')->children([
        html()->text('first-name')->class('form-input')->attribute('data-constraints','@required'),
        //this is the area where I'd like to have some sort of if() functionality
        //and add some sort of conditional
        if($errors->has('first-name')){add an html span with the error}
        html()->label('First Name')->class('form-label')->for('first-name'),
    ])
}}
```

Thanks

**Comment by sebastiandedeyne** [comment]
This currently isn't supported. If anyone wants to spin up a non-breaking PR, feel free to!

**Comment by joshuadegier** [comment]
This should be closed aswel I think @sebastiandedeyne

**Comment by freekmurze** [comment]
Open source is easy 😄
