### ISSUE TITLE
If conditional in blade

### ISSUE THREAD

**Issue by roni-estein** [spatie/laravel-html#39]
Hi Guys, interesting project, I'd like to implement this into a current project, but I think I have to change my thinking on this a bit. Any idea of where how this might be implemented, or if I'm using this in the wrong way. When I am running `$this->validate($request)` in my controller, it will pull my the process back to my blade file form with errors. Where is the best place to embed the output the error code in here as an example:

```
{{
    html()->div()->class('form-wrap')->children([
        html()->text('first-name')->class('form-input')->attribute('data-constraints','@required'),
        //this is the area where I'd like to have some sort of if() functionality
        //and add some sort of conditional
        if($errors->has('first-name')){add an html span with the error}
        html()->label('First Name')->class('form-label')->for('first-name'),
    ])
}}
```

Thanks

**Comment by roni-estein** [comment]
Probably not not the most effective, but this will get you out of a jam if you run into the same issue

```
{{
    html()->div()->class('form-wrap')->children([
        html()->text('first-name')->class('form-input')->attribute('data-constraints','@required'),
        html()->label('First Name')->class('form-label')->for('first-name'),
    ])->if($errors->has('first-name'),function($divElement) use ($errors){
        return $divElement->class('form-wrap')->children([
            html()->span($errors->get('first-name'))->class('form-validation'),
        ]);
    })
}}
```
If anyone could respond with a more laravel way of doing this it would be appreciated.

**Comment by sebastiandedeyne** [comment]
This package should only be used when it's more tedious to write actual html. I'd generally use `html()` for the form fields, but keep the rest in blade.

```html
<div class="form-wrap">

{{ html()->text('first-name')->class('form-input')->attribute('data-constraints','@required') }}

@if($errors->has('first-name'))
    <span>...</span>
@endif

{{ html()->label('First Name')->class('form-label')->for('first-name') }}

</div>
```

Keep it simple :)
