### ISSUE TITLE
Input array names - brackets not rendering

### ISSUE THREAD

**Issue by bbashy** [spatie/laravel-html#40]
I've got an array input that is done like this
```
{{ html()->text('new_answers[]') }}
```
Which rendered this
```
<input type="text" name="new_answers" id="new_answers">
```

How do I get the array brackets to render? I'm sure it used to but since upgrading, it's removed them!

**Comment by sebastiandedeyne** [comment]
Hmm looks like I introduced a regression here. I think I've got a fix ready but gonna have to double check why it was changed in the first place.

I'll tag a solution tomorrow, sorry for the hiccup!

**Comment by bbashy** [comment]
Thanks for the quick response!

_Just a side note; when you put text inside the square brackets, it shows. Round brackets seem to show fine either way_

**Comment by sebastiandedeyne** [comment]
Sorry, wasn't able to get back to this until now.

`dev-master` seems to be stable for me. Could you upgrade to that version and give it a spin? (if possible, please check if multi selects still work as intended)

Gonna tag a bugfix afterç

**Comment by bbashy** [comment]
Tested both and they seem fine!

Thanks!

**Comment by sebastiandedeyne** [comment]
Great! Just tagged `2.0.2`, so the updated version should be discovered by composer soon :)
