### ISSUE TITLE
Checkbox Issue/Question

### ISSUE THREAD

**Issue by timgavin** [spatie/laravel-html#47]
I have a field in my `users` table named `status`, which shows the user's current status and can be either `'active', 'suspended`, or `NULL`.

If I use a checkbox field to show the user's status, and it's anything but`NULL`, the checkbox is checked, which may not be what I want.

### The User Is Active
```
// results in a ticked checkbox, which is expected.
{{ html()->checkbox('status') }}

// results in ticked checkbox, even though I've set the 2nd param to false
{{ html()->checkbox('status', false) }}

```

### The User Is Suspended
```
// results in a ticked checkbox, which is expected because no params have been passed.
{{ html()->checkbox('status') }}

// both result in a ticked checkbox, which is NOT expected, as the $user->status == 'suspended' in the database.
{{ html()->checkbox('status', $user->status, 'active') }}
{{ html()->checkbox('status', false, 'active') }}
```

Now, I know the 2nd parameter is bool, and these were just examples I gave as to a somewhat expected behavior, even though the element wasn't designed this way... regardless, how do tell if the user's status is either `active` or `suspended` when anything other than `NULL` results in a check?

**Comment by sebastiandedeyne** [comment]
When using the method parameters to pass data, the package does an educated guess based on the model data what the checkbox data should be. For cases like this, I recommend using the fluent `active` method instead, since it will trump everything that came before.

This is explained in detail in the docs: https://docs.spatie.be/laravel-html/v1/general-usage/core-concepts#the-difference-between-builder-params-and-element-methods

I'd recommend writing something like this:

```blade
{{ html()->checkbox('status')->active(old('status', $user->status === 'active' ? true : false));
```

Alternatively, you could use Eloquent's accessors/mutators to create a custom property for this.

```php
public function getIsActiveAttribute(): bool
{
    return $user->status === 'active';
}

public function setIsActiveAttribute(bool $active)
{
    $user->status = $active ? 'active' : 'suspended';
}
```

```blade
{{ html()->checkbox('is_active') }}
```

Hope this is what you're looking for! :)

**Comment by timgavin** [comment]
That would be okay, but `Method active does not exist.` :(

```
{{ html()->checkbox('status')->active(old('status', $user->status === 'active' ? true : false)) }}
```

**Comment by sebastiandedeyne** [comment]
I mean `checked` instead of active...

But that doesn't exist either, thought it did! I'll tag a new version with it Monday :)

**Comment by sebastiandedeyne** [comment]
This should work now though:

```
{{ html()->checkbox('status')->attributeIf(old('status', $user->status === 'active'), 'checked', 'checked') }}

**Comment by timgavin** [comment]
Still shows checked when the user is suspended.

**Comment by sebastiandedeyne** [comment]
Version `2.3.0` is tagged with a `checked($bool)` and an `unchecked` method.

{{ html()->checkbox('status')->checked(old('status', $user->status === 'active')) }}

**Comment by timgavin** [comment]
Excellent - thanks!
