### ISSUE TITLE
Input for input fields should be escaped

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-html#5]
A piece of html as a value of an input field won't be rendered correctly.

**Comment by bbashy** [comment]
Is this effecting `html()->button('<i class="icon"></i> Submit')` not allowing HTML to be rendered?

**Comment by sebastiandedeyne** [comment]
Nope, but there was a bug there!

Tagged a fix in v1.1.1 🐛 🔨

**Comment by bbashy** [comment]
@sebastiandedeyne Wonderful, thanks!

`Updating spatie/laravel-html (1.1.0 => 1.1.1): Downloading (100%)`

**Comment by AshboDev** [comment]
Saved my life @bbashy ;)

**Comment by necenzurat** [comment]
```php
{{ html()->form('DELETE', route('campaigns.destroy', ['id' => $campaign->id]))->class('pull-right')->open() }}
{{ html()->button('<span class="glyphicon glyphicon-trash"></span> Șterge')->class('btn btn-danger btn-xs') }}
{{ html()->form()->close() }}
```

Am i doing this right? can we do something about the span/icon tag ?

**Comment by bbashy** [comment]
Just a tip, you don't need to pass an array and the route param to use. You can just pass the collection;
```
{{ html()->form('DELETE', route('campaigns.destroy', $campaign))->class('pull-right')->open() }}
```

**Comment by sebastiandedeyne** [comment]
I think I'd opt to not use the builder for that button, because plain html would be more readable.

Using this html builder is generally useful for things that contain lots of repetition, like form elements, or lots of boilerplate, like form tags with csrf fields.

**Comment by necenzurat** [comment]
yea, i was just trying all the functionality. was doubting keeping this because i wanna alert/confirm with the user before deleting.
Thanks for the tips :)
