### ISSUE TITLE
Form model binding resulting in exception

### ISSUE THREAD

**Issue by chilly2go** [spatie/laravel-html#51]
Hi,

I wanted to generate a form for a model and use it for create/edit so I searched and found your package.
As you stated in your readme it is enough to use `{{ html()->model($myVariable) }}` to bind the Model. As the model method returns an object and laravel tries to output the result it throws an exception `htmlspecialchars() expects parameter 1 to be string, object given (View: /home/pi/www/laraveltest/resources/views/create.blade.php)`
But that is exactly as found on your readme and I could not find a proper method to chain some commands and produce an output that I could use and does not result in an exception.
Using the `@php ()` blade directive helps to not throw the exception but taking the next step (also taken from your readme to exclude erros on my part) I used `{{ html()->input('name') }}` (also tried it chained without the php-blade-directive).
The result is: `<input type="name">` which is not a proper input field, and does not contain anything from my provided model. As I could not find any usage example I can't help but think that this might be a bug / issue.

**Comment by yoeunes** [comment]
i also have the issue, @chilly2go  did you find any work arround ?

**Comment by chilly2go** [comment]
yeah.... I switched to laravelcollective/html which works without exceptions

**Comment by yoeunes** [comment]
Hope @freekmurze fix this soon :/

**Comment by yoeunes** [comment]
html()->model($myVariable) is returning an Html object  ( return $this ), so you could chain it like this : 
```php
{{ html()->model($model)->form('POST', 'url')->open() }}
```
or instead 

```php 
{ html()->modelForm($model, 'POST', 'url')->open() }}
```
i tried this, but it show empty inputs :'(

**Comment by sebastiandedeyne** [comment]
```blade
{{ html()->model($myVariable) }}
```

That's a mistake in the readme, you can't echo after `model`. Gonna fix that example.

What @yoeunes posted is correct and should work:

```blade
{{ html()->model($model)->form('POST', 'url')->open() }}
```

If you're seeing empty inputs, are you using v2 of the package and are you sure that the package service provider is registered? (is your config cache cleared too?)

**Comment by sebastiandedeyne** [comment]
Gonna close this for now, feel free to reopen if you're still having issues here!
