### ISSUE TITLE
Optgroup selected value

### ISSUE THREAD

**Issue by bbashy** [spatie/laravel-html#56]
Having some trouble getting the value to be selected when using a multi-dimensional array.

Maybe I'm formatting it wrong but couldn't work out what to do.

This
```
{{ html()->select('name', ['Optgroup label 1' => ['1' => 'Option 1', '2' => 'Option 2']], 2) }}
```
Generates
```
<select name="name" id="name">
    <optgroup label="Optgroup label 1">
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
    </optgroup>
</select>
```

How do I use optgroup selects?

Thanks.

**Comment by sebastiandedeyne** [comment]
Looks like that wasn't implemented yet. Just tagged `2.6.0` which should do the trick!

See https://github.com/spatie/laravel-html/commit/d280b15a58f561a9b2925e95480abb167d68b8f9

**Comment by bbashy** [comment]
Great, thanks!

I did see `->selectedIf($value === $this->value);` for the optgroup but guessing that's for something else?

**Comment by sebastiandedeyne** [comment]
Where do you mean?

**Comment by bbashy** [comment]
This line https://github.com/spatie/laravel-html/blob/master/src/Elements/Select.php#L87

Working perfectly with the new release :+1:

**Comment by sebastiandedeyne** [comment]
Not sure why that doesn't work actually 😂 

But yeah was a bad place for it, new implementation is more reliable :)

**Comment by bbashy** [comment]
Yeah, I did some debugging and did this but it was an empty string.
```
dd($this->value);
```

**Comment by sebastiandedeyne** [comment]
Iirc that's there for when that line is called after the value has been set, while the builder class sets the value after generating the html.

**Comment by bbashy** [comment]
Right, understand now :)
