### ISSUE TITLE
Retrieving old data for input arrays

### ISSUE THREAD

**Issue by richardselby** [spatie/laravel-html#65]
Say I have some checkboxes as an array:
```
@foreach($permissions as $p)
  {{ html()->checkbox('permission['.$p->id.']') }}
@endforeach
```
If validation fails and we return to the form, the `old()` function won't pick up an old value for these elements; it's looking up `permission[1]` when it needs to look up `permission.1`.

I guess it'd need a helper to convert `permission[1]` to dot notation, but I can't see one that exists yet.

For now, I'm calling `old()` explicitly:
```
@foreach($permissions as $p)
  {{ html()->checkbox('permission['.$p->id.']', old('permission.'.$p->id)) }}
@endforeach
```

**Comment by sebastiandedeyne** [comment]
I'd accept a non-breaking PR that fixes this in this package's `old` method.

https://github.com/spatie/laravel-html/blob/5d7225d5e70bfcd0cbfd696291f3937056133294/src/Html.php#L440
