### ISSUE TITLE
Textarea value broken

### ISSUE THREAD

**Issue by necenzurat** [spatie/laravel-html#74]
Hey, since some time ago, i had something like 

```
{{ html()->textarea('subscribers')->value($phones)->class('form-control')->attribute('rows', 20) }}
```
it throws "The given child should implement `Spatie\Html\HtmlElement` or be a string (View: ..."
fixed it by 
```
{{ html()->textarea('subscribers', $phones)->class('form-control')->attribute('rows', 20) }}
```
What happend?

**Comment by sebastiandedeyne** [comment]
What value is `$phones` holding when you get that error? An array by any chance?

**Comment by necenzurat** [comment]
nope, string, it worked a little wile ago. 

```php
<?php $phones = ""; ?>
@foreach($list->subscribers as $subscriber)
<?php $phones .= $subscriber->phone->phone."\n" ?>
@endforeach
<div class="form-group">
<label for='subscribers'>Numele listei</label> <br />

{{ html()->textarea('subscribers', $phones)->class('form-control')->attribute('rows', 20) }}
<div class="alert alert-info" role="alert">
<span>Campurile sunt: număr de telefon și linile se separa prin rând nou (Enter)</span> <!-- - <a href="demo">Vezi demo aici</a> -->
</div>
</div>
```

**Comment by sebastiandedeyne** [comment]
Hmm can't seem to reproduce this. Are you sure the snippets in your first comment are in the correct order? The second snippet seems more likely to break like this...

**Comment by nyel-dev** [comment]
For people that might encounter this issue, you have to use 
`html()->textarea('body')->text('string')`
instead of
`html()->textarea('body')->value('string')`
