### ISSUE TITLE
Render a Select imput with group-options

### ISSUE THREAD

**Issue by JaimeVirrueta** [spatie/laravel-html#75]
hi, i try to make a select imput with options group but i get this error

`htmlspecialchars() expects parameter 1 to be string, array given (View: C:\xampp\htdocs\webApp_Atlas\resources\views\partials\form\select.blade.php)`

and the array

`array:2 [▼
  0 => array:1 [▼
    "Administración" => array:6 [▼
      "506524b5311d80c0fe2f7477d9476947" => "*Inicio*"
      "d8d953123ce0c43a5e0eadae53b76f7b" => "Usuarios"
      "9f40dc4c98a76ddfffda9061d4f2df37" => "Roles"
      "ee4e98f6a1a161b645c5855fe807c4ea" => "Navegación"
      "7114f3f0dd23c44b371f33ab7e0decfa" => "Historial"
      "0e8e9358840527d11de81e09f35ceceb" => "General"
    ]
1 => array:1 [▼
    "Compañia" => array:7 [▼
      "49f131a4612535cf4f3ec0a022c0d989" => "*Inicio*"
      "c6dec330e46254137a0bee3be13afbb5" => "Empleados"
      "10eebca7ae18f692a4daad59f422b8ca" => "Marca"
      "c4027d0451cef68a19463213dd2d3086" => "Puesto de Trabajo"
      "24d6e3389518d11131a2b1662a6fb13f" => "Sedes"
      "71a81fe6e198fff83b9d0d8512e063e2" => "Unidad Organizativa"
      "5147c3ce8acef1e2c6e834f0fe0ba6d9" => "Areas"
    ]
  ]`

please, can someone help me ?, tranks

**Comment by kubk** [comment]
Can you provide the code please?

**Comment by JaimeVirrueta** [comment]
Sure, 

In the model **PermissionCategory**

	public function listFormWithCategories () {
		$rows = $this::get();
		$parent = $rows->where('parent_id', null)->sortBy('name');
		$val = [];
		foreach ($parent as $key) {
			array_push($val, $this->listFormWithCategoriesSubs($rows, $key));
		}
		return $val;
	}

	private function listFormWithCategoriesSubs ($categories, $category) {
		$tmp = array($category->uuid => '*Inicio*');
		return array($category->name => array_merge($tmp, $categories->where('parent_id', $category->id)->pluck('name', 'uuid')->toArray() ) );
	}


In the controller **PermissionsController**

    public function create() {
        $category = PermissionCategory::element($request->parent)->first();

        $row = new $this->model();
        $row->getParent = $category;

        return View::make('layouts.pages.create', [
            'row'        => $row,
            'sys'        => $this->sys,
            'categories' => PermissionCategory::index()->pluck('name', 'uuid'),
        ]);
    }


In the view **create.blade.php**

<div class="row">
    <div class="col-xs-12 col-md-5">@include('partials.form.select2', [
        'name' => 'category_id', 'title' => 'Categoría:*', 'value' => $row->getParent->uuid, 'list' => $categories
    ]) </div>
</div>

in this view call the a sub-view **select.blade.php**

<div class="form-group form-group-sm {{ $errors->has($name) ? ' has-error' : '' }}">
	{!! isset($title) ? '<label for="'.$name.'" class="control-label">'.$title.'</label>' : '' !!}
	{!! Form::select($name, $list, $value, array_merge(['class'=>'form-control', 'placeholder'=>(isset($placeholder) ? $placeholder : 'Seleccione...')], isset($values) ? $values : [])) !!}
</div>

**Comment by sebastiandedeyne** [comment]
Hi, judging by the `Form::select` snippet, are you sure you're filing this issue in the right repository? We don't support that parameter list.

I think you're looking for this repo: https://github.com/LaravelCollective/html
