### ISSUE TITLE
Radio Element

### ISSUE THREAD

**Issue by oyed** [spatie/laravel-html#8]
Was this element missed on purpose?

**Comment by sebastiandedeyne** [comment]
Nope, I'll add it in soon 😄

**Comment by sebastiandedeyne** [comment]
Added in v1.1.0!

**Comment by vesper8** [comment]
can't find radio in the documentation anywhere though..

**Comment by sebastiandedeyne** [comment]
Looks like it was still missing, added it in. Thanks for the heads up!
