### ISSUE TITLE
Help with radio button

### ISSUE THREAD

**Issue by Jesusfrosalesi** [spatie/laravel-html#80]
How can i retrieve data from controller using model form for radio button?, can you give me a example?

for examle my controller sends  this data->name, this attribute contains "Carl". , i have 3 radio buttons, then i want to only check the radio with value carl, any idea ??. Thanks!

**Comment by sebastiandedeyne** [comment]
Can you please provide a few code samples (controller & view) of what you're trying to achieve?

**Comment by sebastiandedeyne** [comment]
Doing some issue cleanup, feel free to reopen if you're still experiencing issues.
