### ISSUE TITLE
Question about InputTest and Potential False Positives

### ISSUE THREAD

**Issue by paulredmond** [spatie/laravel-html#81]
Hey Guys 👋 

I was looking at adding a few convenience input methods (for date and datetime) but I am a little confused by the tests for `InputTest`.

For example:

https://github.com/spatie/laravel-html/blob/b4108dd504d1f0157854dfaa7e0360d698e5a8b1/tests/Html/InputTest.php#L25-L32

This concern is _not_ checking attributes right now, and even if it was it would only assert that an attribute is present if I am reading `assertEqualXMLStructure` correctly:

https://github.com/spatie/laravel-html/blob/b4108dd504d1f0157854dfaa7e0360d698e5a8b1/tests/Concerns/AssertsHtmlStrings.php#L10-L16

For example, I can change the `InputTest::it_can_create_an_input_with_a_name()` to the following and it still passes:

```php
/** @test */
public function it_can_create_an_input_with_a_name()
{
    $this->assertHtmlStringEqualsHtmlString(
        '<input>',
        $this->html->input('text', 'foo')
    );
}
```

I think the tests are getting false positives, but wanted to check with you guys to see if perhaps I am missing something in understanding before writing my added tests and submitting the PR. I guess I also wonder if you care to add `Html::date()` and `Html::datetime()` as convenience methods similar to `Html::email()` before I submit it as well 😆?

**Comment by sebastiandedeyne** [comment]
Looks like my `Fix html assertions` commit from two weeks ago fixed them by making everything pass instead 😅 

https://github.com/spatie/laravel-html/commit/61c72eb829711373aa6375bdbb7541e4554793e1

Reverted to a modified version of the previous assertion method, looks better now.

Those convenience methods are definitely welcome :)

**Comment by paulredmond** [comment]
Cool, I thought I was going crazy for a minute (still quite possible) 👍
