### ISSUE TITLE
Placeholder for Select element

### ISSUE THREAD

**Issue by bbashy** [spatie/laravel-html#9]
Would it be possible to add `->placeholder()` like inputs for `html()->select()`?

Is there a better way to do it than appending an array to the options?

**Comment by sebastiandedeyne** [comment]
What do you mean by `placeholder`, select tags can't have a placeholder.

Could you post a quick snipped of how you're doing it now?

**Comment by bbashy** [comment]
Sorry for the confusion, I meant appending an entry to the list of options. I did it previously with the LaravelCollective package, like so and this added an entry to the options which was selected if the selected value is null;
```
{{ Form::select('role', $roles, ['class' => 'form-control', 'placeholder' => '- Select Role -']) }}
```

This is how I'm doing it with your package but I won't be using collections all the time for the options.
```
{{ html()->select('role', $roles->prepend('- Select Role -', ''))->class('form-control') }}
```

**Comment by sebastiandedeyne** [comment]
At the moment that's the way to go. I'll look into adding a `placeholder` method to make this easier soon :)

**Comment by bbashy** [comment]
Lovely, thanks!

Ref: https://github.com/LaravelCollective/html/blob/5.4/src/FormBuilder.php#L556-L559

**Comment by vesper8** [comment]
Came here looking for the same thing.. also need it for my app.

The answer here is one way to do it http://stackoverflow.com/questions/5805059/how-do-i-make-a-placeholder-for-a-select-box

If only there was a way to apply the "disabled" flag to the options.. but currently the options only accept key->value

@bbashy how is your example even working? Did you modify the laravel-html package? The ->select() only accepts the name of the input, how are you passing it a 2nd argument? I'm not familiar with collections but don't understand how can you pass it a 2nd argument in any case.

**Comment by bbashy** [comment]
@vesper8 The select actually takes 3 args. I'm just using collection helper to append an item to the list of options for now.

1. name attr
2. options
3. selected value

**Comment by vesper8** [comment]
oh right.. I'm just using it differently from you so got confused. Here's how I use it

```
{{ html()->select('gender')->options(['' => "Select Gender", 'man' => 'man', 'woman' => 'woman'])->class('form-control') }}
```

Well.. looking forward to ->placeholder() then

**Comment by sebastiandedeyne** [comment]
Hi all,

Opened a PR for this. Here are the details:

- Added a `placeholder` method
- If something is already selected in the list, the placeholder won't be auto selected, otherwise it will
- It doesn't have a value. In the Collective package it has an empty value attribute, is this necessary or can I just omit it?

PR: #14

Will merge after feedback :)

**Comment by bbashy** [comment]
I think that looks perfect @sebastiandedeyne 🌸

**Comment by sebastiandedeyne** [comment]
Available in `v1.3.0`!

**Comment by bbashy** [comment]
I'll add a PR but currently it's not got a missing value attribute and thus the browser is sending the text instead.

Form Data
`role: - Select Role -`

**Comment by necenzurat** [comment]
Well, ``
html()->textarea('name')->placeholder('Name')->class('form-control');
``
gives ``
Call to undefined method Spatie\Html\Elements\Textarea::placeholder()
``
A semiclean fix is to use attribute method
``
html()->textarea('name')->class('form-control')->attribute('placeholder', 'Name');
``

**Comment by bbashy** [comment]
@necenzurat You can do a PR for it since the other inputs have the placeholder method.

**Comment by sebastiandedeyne** [comment]
On it already 😬

**Comment by sebastiandedeyne** [comment]
Version `1.4.0` adds a `placeholder(string $placeholder)` method to `Textarea`.

**Comment by necenzurat** [comment]
@bbashy: i know, but don't have the time right in this second.

@sebastiandedeyne: awesome.
