### ISSUE TITLE
Using  the '+' char with a number inside a list select the wrong value !

### ISSUE THREAD

**Issue by houcinecherif** [spatie/laravel-html#93]
Laravel Version: 5.5.*
PHP Version: 7.1.9
Database Driver & Version: MySQL 5.7.19
Description:

Hi,
When I use the '+' char with a number inside a list value I'have the wrong value selected !

Steps To Reproduce :
on this code the selected value is "+2" and "2" , it return two selected items !!
```
{{ html()->select('test', ['1'=>'one','2'=>'two','+2'=>'more than two'], '2')}}
```
on this one its correct :
```
{{ html()->select('test', ['1'=>'one','2'=>'two','+2'=>'more than two'], '+2')}}
```
Is there any workaround without writing loop with HTML ? or should I update the select code :

```php
protected function applyValueToElements($value, Collection $children)
{
    return $children->map(function ($child) use ($value) {
        if ($child instanceof Optgroup) {
            return $child->setChildren($this->applyValueToElements($value, $child->children));
        }

        if ($child instanceof Selectable) {
            return $child->selectedIf($value->contains($child->getAttribute('value')));
        }

        return $child;
    });
}
```

Thanks

**Comment by sebastiandedeyne** [comment]
Fixed in `2.19.2` :)

**Comment by bbashy** [comment]
Think this breaks `modelForm` forms. https://github.com/spatie/laravel-html/commit/09d429dd7b4a311eec32239f9ac515e608f667cf

**Comment by sebastiandedeyne** [comment]
@bbashy Think I know what's going on but wanna write a failing test first. What's the difference between your example and [this](https://github.com/spatie/laravel-html/commit/b06b26d94aa98ce138ea12c1cfd7d4b0e4eb3eb3) test? Could you provide some extra data?

**Comment by bbashy** [comment]
@sebastiandedeyne It would probably be the selected value. That's testing `null`?

I have a modelForm from a model that I'm editing `/resource/1/edit` with `pluck()` option list. Here's something that I found;
```php
$clients = Client::pluck('name', 'id');

// works
{{ html()->select('client_id', $clients, '2')->placeholder('- Select Client -') }}
// works
{{ html()->select('client_id', $clients, (string) $site->client_id)->placeholder('- Select Client -') }}
// doesn't work
{{ html()->select('client_id', $clients $site->client_id)->placeholder('- Select Client -') }}
// doesn't work (this should since it's a modelForm()
{{ html()->select('client_id', $clients)->placeholder('- Select Client -') }}
```

**Comment by sebastiandedeyne** [comment]
Don't think this is solvable. I reverted the change, since the previous behaviour was better.

@houcinecherif Your snippet won't work for now, because in PHP `2 == +2`, and I don't think we can easily fix this without breaking things.
