### ISSUE TITLE
Need element enctype in form

### ISSUE THREAD

**Issue by texnika01** [spatie/laravel-html#98]
need add element  enctype= multipart/form-data for form open
{{ html()->form('PUT', '/update-url', )-element('multipart/form')->open() }}
need for using upload file

**Comment by sebastiandedeyne** [comment]
The `Form` class has an `acceptsFiles` method that adds the `enctype` attribute.

https://github.com/spatie/laravel-html/blob/32ae895f65f89d474430ef1fe4b6c54f65327938/src/Elements/Form.php#L42-L45
